### ISSUE TITLE
Location: Social at A3 Napoli; Mini-conf at Bissel (Confirmed)

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2017-mini-conf#1]
Tracking issue for booking location:

**Requirements**
- All-ages
- Accessible
- Low cost (aka free)

**TODOs**
- [X] Identify potential locations for mini-conf
- [X] Preliminary request for booking space (2016-11-19)
- [x] Identify social location (all-ages friendly)
  - ~Harvest Noon Order in food / potluck?~
  - ~Potluck at a tomesh member's house?~
  - Restaurant in downtown
- [x] Confirm location (we got one! 2016-11-21)
- [x] Update advertisement
