### ISSUE TITLE
Advertising

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2017-mini-conf#2]
Tracking issue for advertising:

**Requirements**
- Email/social media distribution
- Physical advertising

**TODOs**
- [x] Finalize Event description
- [x] Draft poster (aka: 'sweet poster') **end Nov**
- [x] Preliminary Email, in-person and social media advertising **first week Dec**
  - [X] Twitter (start)
  - [X] _Dec 4_ UofT, YorkU, Ryerson, OCADU CS Student Groups
  - [X] _Dec 6_ YorkU CS/Eng Student Groups 
  - [X] _Dec 7_ Social Media (rabble, blogto, now toronto)
  - [X] _Dec 12_ Postering: UofT, OCAD 
- [X] Targeted outreach to community organizations, teachers/directors of student programs
- [x] Final push / new year advertising
  - [x] Twitter 
  - [x] Social Media
  - [x] Postering

**Comment by dcwalk** [comment]
Even description finalized [here](https://github.com/tomeshnet/mini-conf-2017#event-description) and [prelim email](https://github.com/tomeshnet/mini-conf-2017/blob/master/advertising/advertising-email.md)

**Comment by dcwalk** [comment]
Here is the [draft poster](https://matrix.tomesh.net/_matrix/media/v1/download/tomesh.net/onpfqXQmGzoEaPDprJimnXJI)

**Comment by benhylau** [comment]
Does it look better with this `>` char as bullet? Just a suggestion. Along with edits:

```
> participate in hands-on workshops about current toronto mesh and community networking projects
> hear about the history of community networks in our city
> join us in planning how to build a resilient network with internet access for all
```

**Comment by dcwalk** [comment]
@benhylau absolutely! I'm gonna do another pass at the poster shortly, thanks for feedback!

**Comment by dcwalk** [comment]
Finalized(-ish) first version of posters and handbills will be added to the repo, but a previews:
~state-of-posters.pdf~

I have access to B&W printing, but no colour (hence the scheme).

@garrying or others, any thoughts for a better second poster?

(edit: the icons are from the noun project where I have an acct so I was going to add an attribution on slides, website and repo, but I forgot the outline of Toronto is CC-BY, so I'll update the poster/handbills before distributing)

**Comment by garrying** [comment]
@dcwalk A few thoughts:
- At the expense of white-space, should there be a mention of a location?
- The use of a monospaced typeface is probably appropriate given the subject, but I think it reduces readability. Might be worth looking into using Work Sans, or another proportional typeface
- Placing the date to the top-right corner makes it seem separated from the hierarchy flow...especially with the antenna graphic separating the two. I think they should be associated more closely
- I might be reading into the placement of the graphics too much—GTA center reads as a void of activity given that there are objects and lines happening around it
- The highlighting around `City of Toronto` seems like an indicator of focus, but I think it can be made more pronounced if we stick to the GTA boundaries concept
- Text alignments: There's a mix of alignments between the bulleted list, event info, and object labels. Maybe they should be consistent?
- _Explore low-power networks_ with the laptop seems a bit off in terms of representing it
- Handbill: The bullet pointed content not aligned against the left-edge

**Comment by dcwalk** [comment]
Thanks @garrying for all the feedback. I made a bunch of the changes based on your comments
(https://github.com/tomeshnet/mini-conf-2017/tree/poster/advertising -- this includes design files (InDesign)):
- added location
- changed most font to work sans
- moved antenna/adjusted title-date-location flow on posters
- moved antenna into gta on the 'mesh' poster, I think this visually helps?
- unclear about how to address your highlighting comment but think with changes it is okay for now
- streamlined/simplified alignments where possible, most are right aligned now
- didn't change the laptop icon as I couldn't find a better one and swapping text didn't help
- realigned bulleted text

I'll merge and print for tomorrow to provide b&w copies for all to spread about!
