### ISSUE TITLE
Sessions

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2017-mini-conf#3]
Tracking issue for coordinating sessions:

**Requirements**
- 6 sessions: 2 x hands on; 2 x discussion; 2 x framing
- Mix of formats, aim for more engaging 'discussions' 
- Clearly identified session objectives (see [session template](https://github.com/tomeshnet/mini-conf-2017/blob/master/sessions/session-template.md))

**TODOs**
- [x] Initial outreach email for participation
- [x] Confirm Session A
  - [x] Finalized description
  - [x] Presenter
- [x] Confirm Session B
- [x] Confirm Session C
- [x] Confirm Session D 
  - [x] High level description, confirmed presenter
  - [x] Finalized description
- [x] Confirm Session E
  - [x] 5 **/5** presenters confirmed
  - [x] Moderator confirmed
  - [x] Format: Presentations and Moderated Fishbowl
- [x] Confirm Session F
  - [x] 3 **/3** groups confirmed
  - [x] Moderator confirmed
  - [x] Format: Pitches into breakout, email doc with questions & tool
- [x] Confirm Session G
  - [x] Finalized description
  - [x] Presenter

**Comment by dcwalk** [comment]
Links regarding facilitation for participation:
- https://aspirationtech.org/papers/creating_participatory_events
- http://facilitation.aspirationtech.org/index.php?title=Facilitation:Lectures_and_Presentations
- http://facilitation.aspirationtech.org/index.php?title=Agenda:Hacking

**Comment by dcwalk** [comment]
https://unconference.net/unconference-methods-fish-bowl-dialogue/

cc @garrying RE: moderating

**Comment by dcwalk** [comment]
https://en.wikipedia.org/wiki/Fishbowl_(conversation)

**Comment by dcwalk** [comment]
I can't find the original set of instructions, but both of these set out the steps and required facilitator actions @garrying:

http://slitoolkit.ohchr.org/data/downloads/fishbowl.pdf
https://www.facinghistory.org/resource-library/teaching-strategies/fishbowl
